# Language C++, Ubuntu 18
os: linux
dist: bionic
language: cpp

# Services require docker, docker already contains everything
services:
  - docker

# This happens before your build
before_install:
  # Pull the docker image, not cached, caching is slower
  - docker pull yuhanuncitgez/sero_core_opengl:latest

# Notifications, no email, post to slack channel
notifications:
  email: true

script:
  # pass variables TRAVIS_BRANCH and repo to entry-point
  - docker run -v ~/.ccache:/opt/.ccache yuhanuncitgez/sero_core_opengl:latest "$TRAVIS_BRANCH" "$TRAVIS_REPO_SLUG"
